name: Publish Gem

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
      - name: Build gem
        run: |
          gem build github-pages.gemspec
      - name: Publish
        run: |
          gem push github-pages.gem --key ${{ secrets.PAGES_GEM_PUBLISH }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run python 
        run: |
          cd test
          python3 startwatchdog.py --env=prod --split=static
